[window]
dimensions = { columns = 128, lines = 32 }
padding = { x = 5, y = 5 }
dynamic_padding = false
opacity = 0.9
blur = true
decorations = "None"

[font]
normal = { family = "JetBrainsMono Nerd Font" }
size = 12
builtin_box_drawing = false

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Underline", blinking = "Off" }
